name: Terraform

on:
  push:
    branches: [ master ]
    paths: 
    - 'terraform/**'
    - '.github/workflows/terraform.yml'

env:
  config: Release

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.10

    - name: Terraform Init
      id: init
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.STORAGE_RESOURCE_GROUP }}
        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.STORAGE_CONTAINER_NAME }}
      run: terraform init -backend-config="backend_storage_account=$STORAGE_ACCOUNT" -backend-config="backend_storage_container=$CONTAINER_NAME" -backend-config="backend_res_group=$RESOURCE_GROUP"

    - name: Terraform Apply
      id: apply
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.STORAGE_RESOURCE_GROUP }}
        STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
        CONTAINER_NAME: ${{ secrets.STORAGE_CONTAINER_NAME }}
        FUNCTION_STORAGE_ACCOUNT: ${{ secrets.FUNCTION_STORAGE_ACCOUNT }}
        FUNCTION_STORAGE_KEY: ${{ secrets.FUNCTION_STORAGE_KEY }}
      run: terraform apply -auto-approve -no-color -var function_storage_account=$FUNCTION_STORAGE_ACCOUNT -var function_storage_key=$FUNCTION_STORAGE_KEY